# Development config for postgres
version: "3.7"
services:
  db:
    container_name: api-db
    image: api-db
    restart: always
    build: .
    environment:
      - POSTGRES_USER=morphi
      - POSTGRES_PASSWORD=hackme
      - POSTGRES_DB=storage
    # Allow connection from host
    ports:
      - 5432:5432

