name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v1
    
    - name: Install latest nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        default: true
        override: true
    
    - name: Build debug binary
      working-directory: ./api
      run: cargo build

    - name: Launch Postgres
      working-directory: ./postgres
      run: docker-compose up -d --build

    - name: Run test script
      working-directory: ./api
      run: ./test.sh

  #heroku-deploy:
  #  needs: testing
  #  runs-on: ubuntu-latest
  #  if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  #  steps:
  #    - name: Check out repository
  #      uses: actions/checkout@v2
  #
  #    - name: Deploy to Heroku
  #      uses: akhileshns/heroku-deploy@v3.12.12
  #      with:
  #        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
  #        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
  #        heroku_email: ${{ secrets.HEROKU_EMAIL }}

